version: '3.8'

services:
  forge4flame:
    image: qbioturin/forge4flame:latest
    container_name: forge4flame-container
    environment:
      - DOCKER_COMPOSE=ON
    ports:
      - "3839:3838"
    volumes:
      - f4f-data:/usr/local/lib/R/site-library/FORGE4FLAME/FLAMEGPU-FORGE4FLAME/resources/f4f
      - results-data:/usr/local/lib/R/site-library/FORGE4FLAME/FLAMEGPU-FORGE4FLAME/results
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/shared-socket:/tmp/shared-socket
    restart: unless-stopped

  flamegpu:
    image: qbioturin/flamegpu2:latest
    container_name: flamegpu2-container
    environment:
      - DOCKER_COMPOSE=ON
    runtime: nvidia
    stdin_open: true
    tty: true
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - f4f-data:/home/docker/flamegpu2/FLAMEGPU-FORGE4FLAME/resources/f4f
      - results-data:/home/docker/flamegpu2/FLAMEGPU-FORGE4FLAME/results
      - .:/home/docker/flamegpu2/FLAMEGPU-FORGE4FLAME/flamegpu2_results
      - /tmp/shared-socket:/tmp/shared-socket

volumes:
  f4f-data:
    driver: local
  results-data:
    driver: local
