#!/bin/bash
rm -fr build
rm -fr flamegpu2
rm host_rng_state.txt

cd resources
rm -fr __pycache__
rm configuration_file.*
rm MapEncoding.py
rm G.txt
rm run_plan_vector.json
rm rooms_file.xml
rm agents_file.xml
rm -fr plots
rm -fr macro_environment
cd ..

cd src
rm autogenerated_defines.h
rm autogenerated_variables_names.h
cd ..